# Generated by Django 5.0.6 on 2026-06-06 11:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EthiopianFood",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name_en", models.CharField(max_length=200)),
                ("name_am", models.CharField(blank=True, max_length=200)),
                ("display_name", models.CharField(blank=True, max_length=300)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("grains", "Grains & Breads"),
                            ("legumes", "Legumes & Pulses"),
                            ("meat", "Meat & Poultry"),
                            ("dairy", "Dairy & Fermented"),
                            ("vegetables", "Vegetables"),
                            ("drinks", "Drinks"),
                            ("special", "Special Ingredients"),
                        ],
                        max_length=200,
                    ),
                ),
                ("serving_description", models.CharField(max_length=200)),
                ("serving_g", models.FloatField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ephi", "EPHI Ethiopia 2025"),
                            ("fao", "FAO"),
                            ("usda", "USDA"),
                            ("pmc", "PMC Research"),
                            ("heritage", "Heritage Nutrition"),
                        ],
                        default="ephi",
                        max_length=200,
                    ),
                ),
                ("calories_kcal", models.FloatField(default=0)),
                ("fiber_g", models.FloatField(default=0)),
                ("protein_g", models.FloatField(default=0)),
                ("iron_mg", models.FloatField(default=0)),
                ("glycemic_index", models.IntegerField(default=0)),
                ("fermentation_score", models.IntegerField(default=0)),
                ("prebiotic_score", models.IntegerField(default=0)),
                ("inflammatory_index", models.IntegerField(default=0)),
                ("fasting_safe", models.BooleanField(default=False)),
                ("pregnancy_safe", models.BooleanField(default=False)),
                ("diabetes_friendly", models.BooleanField(default=False)),
                ("planner_weekly_safe", models.BooleanField(default=True)),
                ("planner_daily_limit", models.IntegerField(default=2)),
                ("source_citation", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["category", "name_en"],
            },
        ),
        migrations.CreateModel(
            name="MealLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                            ("snack", "Snack"),
                        ],
                        max_length=200,
                    ),
                ),
                ("gut_score", models.IntegerField(default=0)),
                ("fiber_g_total", models.FloatField(default=0)),
                ("protein_g_total", models.FloatField(default=0)),
                ("iron_mg_total", models.FloatField(default=0)),
                ("fermentation_total", models.IntegerField(default=0)),
                ("inflammatory_net", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "family_member",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set if logging for a family member, not the user themselves.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meal_logs",
                        to="users.familymember",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MealLogFood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("servings", models.FloatField(default=1.0)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="foods.ethiopianfood",
                    ),
                ),
                (
                    "meal_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="foods.meallog"
                    ),
                ),
            ],
            options={
                "unique_together": {("meal_log", "food")},
            },
        ),
        migrations.AddField(
            model_name="meallog",
            name="foods",
            field=models.ManyToManyField(
                through="foods.MealLogFood", to="foods.ethiopianfood"
            ),
        ),
        migrations.CreateModel(
            name="DailyNutrition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("gut_score", models.IntegerField(default=0)),
                ("wellness_score", models.IntegerField(default=0)),
                ("fiber_g", models.FloatField(default=0)),
                ("protein_g", models.FloatField(default=0)),
                ("iron_mg", models.FloatField(default=0)),
                ("fermentation_total", models.IntegerField(default=0)),
                ("inflammatory_net", models.IntegerField(default=0)),
                ("meal_count", models.IntegerField(default=0)),
                ("kuriftu_tip", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_nutrition",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
