# Generated by Django 5.0.6 on 2026-06-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0002_ethiopianfood_fat_g_alter_ethiopianfood_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ethiopianfood",
            name="fat_g",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="ethiopianfood",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
