# Generated by Django 5.0.6 on 2026-05-23 13:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OffPeakDeal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "deal_type",
                    models.CharField(
                        choices=[
                            ("spa", "Spa treatment"),
                            ("retreat", "Wellness retreat"),
                            ("yoga", "Yoga / movement session"),
                            ("dining", "Wellness dining"),
                            ("group", "Group package"),
                            ("consult", "Nutritionist consult"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "location",
                    models.CharField(help_text="e.g. Kuriftu Bishoftu", max_length=100),
                ),
                (
                    "original_price_etb",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "discounted_price_etb",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("discount_pct", models.IntegerField()),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("slots_available", models.IntegerField(default=10)),
                ("slots_booked", models.IntegerField(default=0)),
                ("min_gut_score", models.IntegerField(default=0)),
                ("max_gut_score", models.IntegerField(default=100)),
                (
                    "kuriftu_tier_required",
                    models.CharField(default="none", max_length=20),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("booking_url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["valid_from"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("sms", "SMS"),
                            ("push", "Push"),
                            ("email", "Email"),
                            ("telegram", "Telegram"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "notif_type",
                    models.CharField(
                        choices=[
                            ("daily_tip", "Daily wellness tip"),
                            ("weekly_report", "Weekly report"),
                            ("off_peak_deal", "Off-peak deal"),
                            ("score_milestone", "Score milestone"),
                            ("streak", "Streak alert"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("opened", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="notifications.offpeakdeal",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
