# Generated by Django 5.0.6 on 2026-05-23 13:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WellnessPackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "package_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual Premium"),
                            ("family", "Family Plan"),
                            ("group", "Group / Friends"),
                            ("corporate", "Corporate Wellness"),
                            ("kuriftu", "Kuriftu Resort Bundle"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tagline", models.CharField(max_length=200)),
                ("price_etb", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "billing_period",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("annual", "Annual"),
                            ("one_time", "One-time"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("max_members", models.IntegerField(default=1)),
                ("features", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("kuriftu_discount_pct", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["price_etb"],
            },
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("members_count", models.IntegerField(default=1)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="packages.wellnesspackage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
