# Generated by Django 5.0.6 on 2026-05-23 13:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessionalProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("display_name", models.CharField(max_length=100)),
                (
                    "title",
                    models.CharField(help_text="e.g. Dr., RD, CNS", max_length=50),
                ),
                (
                    "specialty",
                    models.CharField(
                        choices=[
                            ("dietitian", "Registered Dietitian"),
                            ("nutritionist", "Certified Nutritionist"),
                            ("gastroenterologist", "Gastroenterologist"),
                            ("general_physician", "General Physician"),
                            ("wellness_coach", "Wellness Coach"),
                            ("yoga_instructor", "Yoga Instructor"),
                            ("fitness_trainer", "Fitness Trainer"),
                        ],
                        max_length=30,
                    ),
                ),
                ("bio", models.TextField(max_length=500)),
                ("languages", models.JSONField(default=list)),
                ("session_types", models.JSONField(default=list)),
                ("license_number", models.CharField(max_length=100)),
                (
                    "license_body",
                    models.CharField(
                        choices=[
                            ("moh", "Ministry of Health Ethiopia"),
                            ("fmhaca", "FMHACA"),
                            ("kuriftu", "Kuriftu Wellness Partner"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_kuriftu_partner", models.BooleanField(default=False)),
                (
                    "session_price_etb",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                (
                    "offpeak_price_etb",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Discounted price for off-peak slots",
                        max_digits=7,
                        null=True,
                    ),
                ),
                ("rating", models.FloatField(default=0.0)),
                ("review_count", models.IntegerField(default=0)),
                ("total_sessions", models.IntegerField(default=0)),
                ("avatar_url", models.URLField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professional_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_verified", "-rating"],
            },
        ),
        migrations.CreateModel(
            name="ExpertSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scheduled_at", models.DateTimeField()),
                ("duration_minutes", models.IntegerField(default=30)),
                ("session_type", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("price_paid_etb", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "platform_fee_etb",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                ("session_notes", models.TextField(blank=True)),
                ("recommendations", models.JSONField(default=list)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expert_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "professional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="experts.professionalprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_at"],
            },
        ),
    ]
