# Generated by Django 5.0.6 on 2026-06-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ethiopianfood",
            name="fat_g",
            field=models.FloatField(
                default=0, help_text="Total fat per 100g edible portion (EPHI 2025)."
            ),
        ),
        migrations.AlterField(
            model_name="ethiopianfood",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
