# Generated by Django 5.0.6 on 2026-07-04 20:24

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business_name", models.CharField(max_length=200)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=30)),
                ("title", models.CharField(max_length=100)),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text="Short description shown under the title",
                        max_length=160,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("spa", "Spa & Wellness Centre"),
                            ("gym", "Gym & Fitness"),
                            ("nutrition", "Nutrition Clinic"),
                            ("restaurant", "Restaurant & Café"),
                            ("food_product", "Health Food Product"),
                            ("pharmacy", "Pharmacy & Supplements"),
                            ("mental", "Mental Health & Therapy"),
                            ("retreat", "Wellness Retreat"),
                            ("other", "Other Health Service"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("sidebar", "Desktop Sidebar"),
                            ("banner", "Mobile Banner"),
                            ("both", "Both"),
                        ],
                        default="both",
                        max_length=10,
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Square or 4:3 image, min 400×400px recommended",
                    ),
                ),
                (
                    "cta_label",
                    models.CharField(
                        default="Learn more",
                        help_text="Button text, e.g. 'Book now', 'Shop', 'Learn more'",
                        max_length=50,
                    ),
                ),
                ("cta_url", models.URLField()),
                (
                    "badge",
                    models.CharField(
                        blank=True,
                        help_text="Optional label e.g. 'New', 'Offer', 'Kuriftu Partner'",
                        max_length=40,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Must be enabled by admin before ad goes live",
                    ),
                ),
                ("starts_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave blank to run indefinitely",
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Higher priority ads appear first. Paid tiers use 10/20/30.",
                    ),
                ),
                (
                    "target_fasting",
                    models.BooleanField(
                        default=False,
                        help_text="Only show during Ethiopian fasting season",
                    ),
                ),
                (
                    "target_pregnant",
                    models.BooleanField(
                        default=False,
                        help_text="Only show to users with pregnancy flag",
                    ),
                ),
                (
                    "target_diabetes",
                    models.BooleanField(
                        default=False, help_text="Only show to users with diabetes flag"
                    ),
                ),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("clicks", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-priority", "-starts_at"],
            },
        ),
    ]
