# Generated by Django 5.0.6 on 2026-07-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="amount_etb",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Amount agreed in ETB. Auto-filled from tier but can be overridden.",
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="invoice_note",
            field=models.TextField(
                blank=True,
                help_text="Internal notes about billing, discounts, or payment arrangement",
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="payment_date",
            field=models.DateField(
                blank=True, help_text="Date payment was confirmed received", null=True
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="payment_reference",
            field=models.CharField(
                blank=True,
                help_text="Bank transfer ref, CBE Birr transaction ID, or receipt number",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Unpaid — awaiting payment"),
                    ("paid", "Paid — ready to activate"),
                    ("overdue", "Overdue — payment lapsed"),
                    ("complimentary", "Complimentary — no charge"),
                ],
                default="unpaid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="tier",
            field=models.CharField(
                choices=[
                    ("basic", "Basic — 30 days, sidebar only"),
                    ("standard", "Standard — 60 days, sidebar + banner"),
                    ("premium", "Premium — 90 days, all placements + priority"),
                ],
                default="basic",
                help_text="Determines price, duration, and placement options",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="badge",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="cta_label",
            field=models.CharField(default="Learn more", max_length=50),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="ends_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Auto-set from tier duration on save if left blank",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Admin must manually activate after confirming payment",
            ),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="priority",
            field=models.IntegerField(
                default=0,
                help_text="Higher = shown first. Premium=30, Standard=20, Basic=10",
            ),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="tagline",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="target_diabetes",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="target_fasting",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="target_pregnant",
            field=models.BooleanField(default=False),
        ),
    ]
