# Generated by Django 5.0.6 on 2026-07-07 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_advertisement_amount_etb_advertisement_invoice_note_and_more"),
    ]

    operations = []
