# Generated by Django 5.0.6 on 2026-06-12 12:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('am', 'Amharic')], default='en', max_length=10)),
                ('sms_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('member_type', models.CharField(choices=[('adult', 'Adult'), ('child', 'Child'), ('elder', 'Elder'), ('pregnant', 'Pregnant'), ('infant', 'Infant')], max_length=20)),
                ('age_years', models.IntegerField(blank=True, null=True)),
                ('diet_type', models.CharField(blank=True, max_length=20)),
                ('has_diabetes', models.BooleanField(default=False)),
                ('has_anemia', models.BooleanField(default=False)),
                ('current_gut_score', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not', 'Prefer not to say')], max_length=20)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('primary_goal', models.CharField(choices=[('gut_health', 'Improve gut health'), ('weight_balance', 'Weight balance'), ('energy', 'Boost energy'), ('stress', 'Reduce stress'), ('sleep', 'Better sleep'), ('immunity', 'Build immunity'), ('mindfulness', 'Mindful living'), ('general', 'General wellness')], default='general', max_length=30)),
                ('secondary_goals', models.JSONField(default=list)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary (desk job, little exercise)'), ('light', 'Light (1–2 days exercise/week)'), ('moderate', 'Moderate (3–4 days/week)'), ('active', 'Active (5+ days/week)')], default='moderate', max_length=20)),
                ('diet_type', models.CharField(choices=[('omnivore', 'Omnivore'), ('fasting', 'Ethiopian Orthodox fasting'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('no_pork', 'No pork'), ('diabetic', 'Diabetic-friendly')], default='omnivore', max_length=20)),
                ('is_pregnant', models.BooleanField(default=False)),
                ('has_diabetes', models.BooleanField(default=False)),
                ('has_hypertension', models.BooleanField(default=False)),
                ('has_anemia', models.BooleanField(default=False)),
                ('is_fasting_season', models.BooleanField(default=False)),
                ('kuriftu_guest', models.BooleanField(default=False)),
                ('kuriftu_membership_tier', models.CharField(choices=[('none', 'None'), ('standard', 'Standard'), ('premium', 'Premium')], default='none', max_length=20)),
                ('current_gut_score', models.IntegerField(default=0)),
                ('current_wellness_score', models.IntegerField(default=0)),
                ('wellness_streak_days', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
